refactor: use angular signals, standalone component
willmendesneto/ngx-skeleton-loader pull request #179
Opened 2024-10-04 18:36 UTC by lekhmanrus

**Please check if the PR fulfills these requirements**

- [x] The commit messages follow these [guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** _(check one with "x")_

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other. Please describe:

If it is a Bugfix, please describe the root cause and what could have been done to prevent it…

**What is the current behavior?** _(You can link to an open issue here, add screenshots…)_
Regular `@Input`s used as well as `OnChanges` hook.

**What is the new behavior?**
Angular Signals with build-in validation; refactored to standalone components.

**Does this PR introduce a breaking change?** _(check one with "x")_

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: …

**Other information (if applicable)**:
close #158

I would suggest using versions consistent with major Angular versions. Let's say ngx-skeleton-loader v18 for Angular v18, etc.
---

_Please @mention @people to review this PR…_
@willmendesneto

2024-12-16 15:18 UTC, willmendesneto requested changes
🚀  Thanks for your contribution. 🚀 

In regards of your question of Angular deps, this package (along all angular modules in general) should cover the actively supported versions. More details in these links:
-  https://angular.dev/reference/versions#actively-supported-versions
- https://angular.dev/reference/releases#actively-supported-versions

In summary, nicely done! I'm adding some comments since some checks were removed when they shouldn't and the pull request is dealing with 2 different issues at the same time, which increases the level of validation.

Feel free to ping if you need more info

2024-12-16 15:18 UTC, willmendesneto commented on projects/ngx-skeleton-loader/src/lib/ngx-skeleton-loader.component.spec.ts
> -    it('should console 3 errors if `animation`, `appearance` and `count` receives invalid options in development mode', () => {
These tests are still relevant for consumers. Could you add them back, and the code to support those tests as well, please?

2024-12-16 15:18 UTC, willmendesneto commented on projects/ngx-skeleton-loader/src/lib/ngx-skeleton-loader.component.ts
> -    const allowedAnimations = ['progress', 'progress-dark', 'pulse', 'false'];
The code needs all these validations still. Could you add them back, please?

2024-12-16 15:18 UTC, willmendesneto commented on projects/ngx-skeleton-loader/src/lib/ngx-skeleton-loader.html
> +    @if (appearanceValue  === 'custom-content') {
👏 👏 👏

2024-12-16 15:18 UTC, willmendesneto commented on src/app/app.module.ts
> +} from 'ngx-skeleton-loader';
Thanks, mate!

2025-01-17 09:12 UTC, TomLBarden commented
Hi! The issue this PR resolves is currently blocking my upgrade to Angular 19. Any chance of some movement on this in the near future?

2025-01-23 14:42 UTC, willmendesneto commented
Hey @TomLBarden I'm working on to apply these changes and upgrade this library to v19 properly (unfortunately, looks like this pull request is abandoned).

In the meantime, if you want to remove your blocker feel free to follow the changes as described in this issue comment https://github.com/willmendesneto/ngx-skeleton-loader/issues/183#issuecomment-2609906475

2025-01-23 14:44 UTC, willmendesneto commented on projects/ngx-skeleton-loader/src/lib/ngx-skeleton-loader.component.ts
> -    const allowedAnimations = ['progress', 'progress-dark', 'pulse', 'false'];
Good point @lekhmanrus. Let's keep that way <3

2025-01-23 14:46 UTC, willmendesneto commented
@lekhmanrus Could you solve the conflicts on the `package-lock.json`, please? I can solve that by EOD, if I didn't get any replies from your side

2025-01-24 13:13 UTC, willmendesneto approved these changes

2025-01-24 13:14 UTC, willmendesneto commented
Thanks for the contribution, @lekhmanrus ! Massive kudos! 
![](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGI4cjZuc2h1bHpmbzhudnpwc3YwbnN3N3BpZDJxeng3MWlvcHhtaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/d9a75A50T9AvJr0taw/giphy.gif)

2025-01-24 13:14 UTC, merged

2025-01-24 15:10 UTC, willmendesneto commented
And I'm more than happy to announce that: it's alive!

Please upgrade your projects to use `ngx-skeleton-loader@10.0.0` and enjoy these changes in your app!


Once again, thanks @lekhmanrus for that! cc/ @TomLBarden @chimurai @yharaskrik